CREATE TABLE Favourite (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
);

CREATE TABLE Necessity (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
);

CREATE TABLE Account (
    id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    fname NVARCHAR(255) NOT NULL,
    lname NVARCHAR(255) NOT NULL,
    address NVARCHAR(255) NOT NULL,
    income INT NOT NULL,
);

CREATE TABLE AccountFavourite (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    accountId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(id),
    favouriteId INT NOT NULL FOREIGN KEY REFERENCES Favourite(id),
);

CREATE TABLE AccountNecessity (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    accountId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Account(id),
    necessityId INT NOT NULL FOREIGN KEY REFERENCES Necessity(id),
);

CREATE TABLE Location (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
);

CREATE TABLE Place (
    id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    name NVARCHAR(255) NOT NULL,
    priceStart INT NOT NULL,
    priceEnd INT NOT NULL,
    unit NVARCHAR(255) NOT NULL,
    timeStart TIME NOT NULL,
    timeEnd TIME NOT NULL,
    note NVARCHAR(255) NOT NULL,
    locationId INT NOT NULL FOREIGN KEY REFERENCES Location(id),
);